CREATE TABLE IF NOT EXISTS STUDENT(
    ROLL_NO TEXT ,
    NAME TEXT NOT NULL,
    ADDRESS TEXT,
    PHONE TEXT,
    AGE INTEGER
);
INSERT INFO STUDENT (ROLL_NO,NAME,ADDRESS,PHONE,AGE)VALUES
('1','zaidi','KOHAT','*******',9),
('2','yousaf','PESHAWER','***********',49),
('3','hadi','MULTAN','***',20),
('4','shayan','ISLAMBAD','***',18)

SELECT * FROM STUDENT;

select * from student where AGE=18 and ADDRESS='ISLAMBAD'

select * from student where NAME='HADI' and ADDRESS='MULTAN'


DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE IF NOT EXISTS PRODUCT(
    PRO_ID TEXT PRIMARY KEY,
    PRO_NAME TEXT,
    PRO_PRICE INTEGER,
    PRO_COM TEXT
);

INSERT INTO PRODUCT (PRO_ID,PRO_NAME,PRO_PRICE,PRO_COM )
VALUES
    ('111','MOTHER ',100,'16')
    ('112','DAD ',250,'17')
    ('113','DVD ',220,'18')
    ('114','Drive',3700,'19')

SELECT * FROM PRODUCT;

SELECT PRO_NAME,PRO_PRICE
FROM PRODUCT
WHERE RO_PRICE=(SELECT MIN(PRO_PRICE) FROM PRODUCT);
 
 SELECT PRO_NAME,PRO_PRICE
FROM PRODUCT
WHERE RO_PRICE=(SELECT MIN(PRO_PRICE) FROM PRODUCT);
 