CREATE TABLE IF NOT EXISTS STUDENT(
    ROLL_NO TEXT PRIMARY KEY,
    NAME TEXT NOT NULL,
    ADDRESS TEXT,
    PHONE TEXT,
    AGE INTEGER
);
INSERT INFO STUDENT (ROLL_NO,NAME,ADDRESS,PHONE,AGE)VALUES
('1','ALI','KOHAT','*******',19),
('2','ABBAS','PESHAWER','***********',19),
('3','ASKARI','MULTAN','***',25),
('4','ABDULLAH','ISLAMBAD','***',28)
('5','AYAN','MURREE','****',32)

SELECT * FROM STUDENT;

SELECT * FROM STUDENT WHERE AGE=19 AND ADRESS='KOHAT';

SELECT * FROM STUDENT WHERE AGE=19 AND ADRESS='PESHAWER';

SELECT * FROM STUDENT WHERE AGE=28 AND NAME='ABDULLAH';

SELECT * FROM STUDENT WHERE AGE=32 AND NAME='AYAN';

SELECT * FROM STUDENT WHERE NAME='ABBAS' AND AGE='19';

DROP TABLE IF EXISTS PRODUCT;

# CREATE TABLE

DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE IF NOT EXISTS PRODUCT(
    PRO_ID TEXT PRIMARY KEY,
    PRO_NAME TEXT,
    PRO_PRICE INTEGER,
    PRO_COM TEXT
);

INSERT INTO PRODUCT (PRO_ID,PRO_NAME,PRO_PRICE,PRO_COM )
VALUES
    ('101','MOTHER BOARD',300,'16')
    ('102','DAD BOARD',200,'17')
    ('103','DVD DRIVE',320,'18')
    ('104','MOU SE',3200,'19')

SELECT * FROM PRODUCT;

SELECT PRO_NAME,PRO_PRICE
FROM PRODUCT
WHERE RO_PRICE=(SELECT MIN(PRO_PRICE) FROM PRODUCT);
 
 SELECT PRO_NAME,PRO_PRICE
FROM PRODUCT
WHERE RO_PRICE=(SELECT MIN(PRO_PRICE) FROM PRODUCT);
 